#!/bin/sh
set -e

FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS --no-preview $*"

exec 3<&0
alacritty \
    -o window.class.general=fzf-dmenu \
    -o window.class.instance=fzf-dmenu \
    -o window.decorations=full \
    -o window.dimensions.columns=80 \
    -o window.dimensions.lines=8 \
    -o window.title=fzf-dmenu \
    -e /bin/sh -c "fzf $* <&3 1>&4" \
    4>&1
