#!/bin/sh
set -e

# git-rev-parse alias to fuzzy find SHA if not specified.
# not in git config alias due to being a plumbing command, see note in ./git

# Most rev-parse flags don't require (or accept) a commit, so for simplicity's
# sake let's only run fzsha if we have no args.
if [ $# -eq 0 ]; then
    git fzsha rev-parse "$@"
else
    git rev-parse "$@"
fi
